### PR TITLE
Fix boolean environment variables in the configuration (fix #22)

### LINKED ISSUE #22: Comparison for boolean variables in configuration is still faulty
The last attempt to fix variable comparison for environment variables in the configuration file in https://github.com/YOURLS/docker-yourls/commit/71832c631cd4cb174070d54d3136aa2e413edee8 doesn't work for booleans which have `true` as default value.

For example
`define( 'YOURLS_UNIQUE_URLS', filter_var(getenv('YOURLS_UNIQUE_URLS'), FILTER_VALIDATE_BOOLEAN) ?: true );`
will always evaluate to true, even if `getenv('YOURLS_UNIQUE_URLS')` is false.

Because if set to false, the statement would be:
`define( 'YOURLS_UNIQUE_URLS', false ?: true );`
which results in true.

The fix would be to delete the comparsion, because the filter will always return `true` or `false`. For example:
`define( 'YOURLS_UNIQUE_URLS', filter_var(getenv('YOURLS_UNIQUE_URLS'), FILTER_VALIDATE_BOOLEAN));`

### PR DESCRIPTION
**Pull request by thechristschn**
Currently `filter_var(getenv('ENV_VAR'), FILTER_VALIDATE_BOOLEAN) ?: true` will always evaluate to `true`.

We need string comparison for environment variables which have true as default value, because `filter_var(getenv('ENV_VAR'), FILTER_VALIDATE_BOOLEAN)` will be false if ENV_VAR is "false" or empty. Otherwise wo could not differentiate between false and unset variable.

### CODE REVIEW

File: config-docker.php [hunk 1]
```diff
@@ -43,12 +43,12 @@
 /** Allow multiple short URLs for a same long URL
  ** Set to true to have only one pair of shortURL/longURL (default YOURLS behavior)
  ** Set to false to allow multiple short URLs pointing to the same long URL (bit.ly behavior) */
-define( 'YOURLS_UNIQUE_URLS', filter_var(getenv('YOURLS_UNIQUE_URLS'), FILTER_VALIDATE_BOOLEAN) ?: true );
+define( 'YOURLS_UNIQUE_URLS', getenv('YOURLS_UNIQUE_URLS') == 'false' ? false : true );
```
Comment (LeoColomb) [inline config-docker.php]: OK for the way to go, but it can be linted to:

```suggestion
define( 'YOURLS_UNIQUE_URLS', getenv('YOURLS_UNIQUE_URLS') !== 'false' );
```

File: config-docker.php [hunk 2]
```diff
@@ -43,12 +43,12 @@
...
 
 /** Private means the Admin area will be protected with login/pass as defined below.
  ** Set to false for public usage (eg on a restricted intranet or for test setups)
  ** Read http://yourls.org/privatepublic for more details if you're unsure */
-define( 'YOURLS_PRIVATE', filter_var(getenv('YOURLS_PRIVATE'), FILTER_VALIDATE_BOOLEAN) ?: true );
+define( 'YOURLS_PRIVATE', getenv('YOURLS_PRIVATE') == 'false' ? false : true );
```
Comment (LeoColomb) [inline config-docker.php]: Same here.

```suggestion
define( 'YOURLS_PRIVATE', getenv('YOURLS_PRIVATE') !== 'false' );
```

File: config-docker.php [hunk 3]
```diff
@@ -62,7 +62,7 @@
 
 /** Debug mode to output some internal information
  ** Default is false for live site. Enable when coding or before submitting a new issue */
-define( 'YOURLS_DEBUG', filter_var(getenv('YOURLS_DEBUG'), FILTER_VALIDATE_BOOLEAN) ?: false );
+define( 'YOURLS_DEBUG', filter_var(getenv('YOURLS_DEBUG'), FILTER_VALIDATE_BOOLEAN));
```
Comment (LeoColomb) [inline config-docker.php]: 👍

Comment (LeoColomb) [reply config-docker.php]: Oh, be careful, need a space.

```suggestion
define( 'YOURLS_DEBUG', filter_var(getenv('YOURLS_DEBUG'), FILTER_VALIDATE_BOOLEAN) );
```

File: config-docker.php (hunk 1 above)
Comment (thechristschn) [reply config-docker.php]: I know. But I think in my version it is more clearly what the default value is.
I can change it, but people have to think twice (or more often) what will happen if the variable ist not set.

Comment (LeoColomb) [reply config-docker.php]: I definitely prefer the shorten version.
All these variables are explained multiple times in documentation, and their names are sufficiently explicit to raise concerns.
People usually don't look at this file but the docs (don't forget this file is into distributed into a docker layer, not that easy to find and read).

Comment (thechristschn) [reply config-docker.php]: Ok, fixed.

**Comment by YKWeyer** [comment]
🤔 The merged version evaluates everything that is not `"false"` to be true. It should still be possible to use `0` or `1` as values, since they are valid booleans as well, don't you think?

The original issue could be solved using the Null Coalesce Operator operator

For PHP7+:
```php 
define( 'YOURLS_DEBUG', filter_var(getenv('YOURLS_DEBUG') ?? true, FILTER_VALIDATE_BOOLEAN) );
```
Or for more explicit logic (or older PHP versions compatibility):
```php 
define( 'YOURLS_DEBUG', filter_var((isset(getenv('YOURLS_DEBUG')) ? getenv('YOURLS_DEBUG') : true), FILTER_VALIDATE_BOOLEAN) );
```

This way, if `getenv('YOURLS_DEBUG')` is not set, the default value `true` is used. If there is a value provided, it gets validated as a boolean.

@LeoColomb what do you think? Should I open a MR to fix it?

**Comment by LeoColomb** [comment]
Good catch, thanks @YKWeyer!
I'm globally OK for a PR, but it seems the `getenv` always return a no-null value: https://secure.php.net/manual/en/function.getenv.php
Then not sure it will work as expected…

**Comment by LeoColomb** [comment]
The best I could think of:
```php
getenv('Y') === false ?: filter_var(getenv('Y'), BOOL)
```
But very sensitive.

**Comment by YKWeyer** [comment]
My bad, you are absolutely right!

So the whole line would be:
```php
define( 'ENV_VAR',  getenv('ENV_VAR') === false ? true : filter_var(getenv('ENV_VAR'), FILTER_VALIDATE_BOOLEAN) );
```

It's perhaps a matter of taste, but I don't like how confusing this syntax can get. It might make sense to keep the default value at the end of the line, for consistency with other parameters:
```php
define( 'ENV_VAR',  getenv('ENV_VAR') !== false ? filter_var(getenv('ENV_VAR'), FILTER_VALIDATE_BOOLEAN) : true );
```

**Comment by LeoColomb** [comment]
```php
define( 'ENV_VAR',  getenv('ENV_VAR') === false ?: filter_var(getenv('ENV_VAR'), FILTER_VALIDATE_BOOLEAN) );
```

I prefer the shorten version that explicit one. https://github.com/YOURLS/docker-yourls/pull/23#discussion_r264008689

**Comment by thechristschn** [comment]
@LeoColomb can you update the official image on dockerhub?

**Comment by LeoColomb** [comment]
It's on its way, but let's wait for the @YKWeyer's fix.
